D2 : routineNotCompleteOrServiceInProgress handling
fenugrec/freediag pull request #88
Opened 2023-10-10 00:20 UTC by aaeegg

D2 : If we get a routineNotCompleteOrServiceInProgress response, discard it and keep listening until we get the final response. This is necessary for requests that return a few routineNotCompleteOrServiceInProgresses before they complete, such as clearDiagnosticInformation on AW50-42.

This makes cleardtc work on AW50-42 (#84), but the interface will still increase its timeout after cleardtc on AW50-42 which can cause problems with other operations afterwards (does not fix #87).

2023-10-10 02:20 UTC, fenugrec requested changes
some minor style comments. Have you tried running uncrustify with our included .cfg ? I'm not enforcing it systematically (yet) but it should work acceptably.

Can you rework the commit message to follow the usual pattern (short first line summary, blank line, then explanation)

2023-10-10 02:20 UTC, fenugrec commented on scantool/diag_l2_d2.c
> +			diag_freemsg(rmsg);
missing { }

2023-10-10 02:20 UTC, fenugrec commented on scantool/diag_l2_d2.c
> +	} while(rmsg->len==3 && rmsg->data[0]==0x7e && rmsg->data[1]==msg->data[0] && rmsg->data[2]==0x23);
space between `while` and `(`

2023-10-10 02:55 UTC, aaeegg commented
Amended with style changes.

2023-10-10 15:45 UTC, fenugrec commented
Would it be possible to cover this in our 850 testsuite ? I think multiple responses should work with the carsim backend, it would be nice to have at least some coverage for this

2023-10-11 03:01 UTC, aaeegg commented
Test added. I put the routineNotCompleteOrServiceInProgress test in dtc instead of cleardtc, because freediag won't take Yes/No responses from the ini file, so cleardtc would just sit forever in cli_basic_get_input waiting for keyboard input.

2023-10-11 15:02 UTC, fenugrec commented
> Test added. I put the routineNotCompleteOrServiceInProgress test in dtc instead of cleardtc, because freediag won't take Yes/No responses from the ini file, so cleardtc would just sit forever in cli_basic_get_input waiting for keyboard input.

Sounds good. Thanks for taking the time to add those tests.

Rebased + merged at c546172c2d1df726f80ab19369ae0d48b943e0d5  !

2023-10-11 15:02 UTC, closed without merging